### ISSUE TITLE
Agregar validaciones de producto

### ISSUE THREAD

**Issue by FelipeDelZoppo** [Grupo-9-Anita/e-commerce-tpi-backend#31]
Agregar validaciones faltantes a producto como espacios al principio y al final

**Comment by JaaF97** [comment]
Te dejo los cambios exactos @FelipeDelZoppo para que cuando vuelvas del viaje te acuerdes bien cuales eran (como te envidio hermano)

Este que lo hablamos en soporte:
- Se permite registrar productos con el mismo nombre si varían en color. No se permitirá registrar dos productos con nombre y color idénticos.
- Si ya existe un producto con el mismo nombre y color, el sistema debe notificar al usuario mediante un mensaje de error.

Color pasa a ser **OBLIGATORIO**, y tiene estas validaciones:
- El color debe tener entre 3 y 20 caracteres.
- El color debe contener solo letras.

Lo de los espacios, en producto es para nombre y descripción:
- Antes de crear el producto, el sistema debe eliminar automáticamente los espacios en blanco al final del nombre.
- Antes de crear el producto, el sistema debe eliminar automáticamente los espacios en blanco al final de la descripción.

Despues, en marca, categoría y subcategoria acordate que pasa lo mismo con nombre

**Comment by FelipeDelZoppo** [comment]
Criterios de aceptacion a agregar:

- [ ] El color debe tener entre 3 y 20 caracteres.
- [ ] El color debe contener solo letras.
- [ ] Los espacios al principio y al final del color no se tendrán en cuenta
- [ ] Los espacios al principio y al final del nombre no se tendrán en cuenta
- [ ] Los espacios al principio y al final de la descripcion no se tendrán en cuenta
