### ISSUE TITLE
Fix: Productos con mismo nombre pero distinto color

### ISSUE THREAD

**Issue by FelipeDelZoppo** [Grupo-9-Anita/e-commerce-tpi-backend#33]
Arreglar funcionalidad para que se pueda crear dos productos con mismo nombre pero distinto color.

**Comment by JaaF97** [comment]
Te dejo los cambios exactos @FelipeDelZoppo para que cuando vuelvas del viaje te acuerdes bien cuales eran (como te envidio hermano)

Este que lo hablamos en soporte:
- [ ] Se permite registrar productos con el mismo nombre si varían en color. No se permitirá registrar dos productos con nombre y color idénticos.
- [ ] Si ya existe un producto con el mismo nombre y color, el sistema debe notificar al usuario mediante un mensaje de error.

**Comment by FelipeDelZoppo** [comment]
Criterios de aceptacion a agregar:

- [ ] Color es obligatorio
- [ ] Color debe tener entre 3 y 20 caracteres 
- [ ] Color debe contener solo letras
- [ ] Se permite registrar productos con el mismo nombre si varían en color. No se permitirá registrar dos productos con nombre y color idénticos.
- [ ] Si ya existe un producto con el mismo nombre y color, el sistema debe notificar al usuario mediante un mensaje de error.
