### ISSUE TITLE
Prueba N°11: Validar la actualización de stock después de cada venta

### ISSUE THREAD

**Issue by juliansalvucci** [Grupo-9-Anita/e-commerce-tpi-backend#69]

**Comment by FelipeDelZoppo** [comment]
Al ser prueba unitaria, se valida el metodo del modifyProductService en donde se hace el descuento de stock. No se valida todo el camino desde que se crea un pedido nuevo, eso seria un test de integracion

**Comment by FelipeDelZoppo** [comment]
### Prueba N°11: Validar la actualización de stock después de cada venta

- **Historia de Usuario:** Registrar Pedido
- **Requerimiento:** El sistema debe actualizar automáticamente el stock de los productos incluidos en el pedido
- **Descripción:** Valida que, tras la finalización de un pedido, el sistema actualice el stock de los productos vendidos, reflejando la cantidad disponible en stock.
- **Técnica de diseño utilizada:** Transición de Estados
    - Estado stock inicial (stock antes de que se confirme un pedido)
    - Estado pedido en proceso (estado transitorio cuando un pedido se está registrando, pero el stock aún no ha sido actualizado)
    - Estado stock actualizado (se confirma la compra del pedido y se actualiza el stock para reflejar el stock disponible real)
    - Estado error (se cancela la compra del pedido, por lo que el stock no debe actualizarse)
- Feature: Validar la actualización de stock después de cada venta
    
    **Background:**
    Dado que la aplicación está procesando la compra de un cliente
    **And** se debe actualizar el stock automáticamente cuando se confirma la compra
    
    ---
    
    **Scenario Outline**: Validar la actualización de stock después de cada venta
    
    **Given** un cliente está finalizando la compra de un pedido
    **When** se termina de procesar la compra
    **Then** el sistema <resultadoEsperado>
    **And** <salidaEsperada>
    
    **Examples**:

Estado 1 | Estado 2 | Estado 3 | resultadoEsperado | salidaEsperada
-- | -- | -- | -- | --
Estado stock inicial | Estado pedido en proceso | Estado stock actualizado | Se actualiza el stock en base al pedido realizado | No muestra errores
Estado stock inicial | Estado pedido en proceso | Estado error | Se mantiene el stock igual a antes de que se haya intentado realizar el pedido | No muestra errores
